In [53]:
!pip3 install flask

Defaulting to user installation because normal site-packages is not writeable
Collecting flask
  Downloading flask-3.1.0-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 1.2 MB/s eta 0:00:01
Collecting blinker>=1.9
  Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Requirement already satisfied: click>=8.1.3 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from flask) (8.1.8)
Requirement already satisfied: Werkzeug>=3.1 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from flask) (3.1.3)
Requirement already satisfied: Jinja2>=3.1.2 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from flask) (3.1.5)
Requirement already satisfied: importlib-metadata>=3.6 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from flask) (8.6.1)
Collecting itsdangerous>=2.2
  Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: zipp>=3.20 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=3.6->flask) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/sooreoluwa/Library/Python/3.9/lib/python/site-packages (from Jinja2>=3.1.2->flask) (3.0.2)
Installing collected packages: itsdangerous, blinker, flask
Successfully installed blinker-1.9.0 flask-3.1.0 itsdangerous-2.2.0
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.

In [46]:
import pandas as pd
import requests
import json
import time
import csv
import io
import Levenshtein
from urllib.parse import urlparse
from flask import Flask, jsonify
from requests.auth import HTTPBasicAuth

In [47]:
def fetch_data_csv(url):
    # Make the request
    response = requests.get(url)
    if response.status_code == 200:
        # Return the CSV data
        csv_data = response.text
        csv_reader = csv.reader(io.StringIO(csv_data))

        # Convert CSV to a list of rows
        data = [row for row in csv_reader]
        return data
    else:
        print(f"Failed to fetch data. Status code: {response.status_code}. Reason: {response.reason}")
        
        return []

# Function to fetch exchanges with pagination
def fetch_exchanges(url):
    page = 1
    all_exchanges = []
    
    while True:
        # Add the page parameter to the request
        params = {"per_page": 250, "page": page} 
        try:
            # Make the request
            response = requests.get(url, params=params)
            # Check if the request was successful
            if response.status_code == 200:
                data = response.json()
                # If no data is returned, stop the loop
                if not data:
                    break
                # Add the fetched data to the list
                all_exchanges.extend(data)
                print(f"Fetched page {page} with {len(data)} exchanges.")
                # Move to the next page
                page += 1
                # Add a delay to avoid hitting the rate limit
                time.sleep(1) 
    
            elif response.status_code == 429:
                # Handle rate limit error
                print("Rate limit exceeded. Waiting for 10 seconds before retrying...")
                time.sleep(60)  # Wait 60 seconds before retrying
            
            else:
                # Handle other errors
                print(f"Failed to fetch data. Status code: {response.status_code}. Reason: {response.reason}")
                break
        
        except requests.exceptions.RequestException as e:
            # Handle network errors
            print(f"Network error: {e}")
            break
    
    return all_exchanges

# Function to fetch exchanges from DeFi Llama
def fetch_exchanges_II(url):
    # Make the request
    response = requests.get(url)
    if response.status_code == 200:
        # Return the JSON data
        return response.json() 
    else:
        print(f"Failed to fetch data. Status code: {response.status_code}. Reason: {response.reason}")
        
        return []

# Function to fetch the blacklist url
def blacklist_toMap(items):
    # Create a list to store the name-url mappings
    blacklist_map = []

    # Process each URL in the blacklist
    for url in items:
        # Extract the text before the domain extension
        name = url.split('.')[0]
        # Create a dictionary for the name and URL
        blacklist_map.append({'name': name, 'url': url})

    return blacklist_map


def fetch_bank_institutions(auth_url, institutions_url, client_id, client_secret):
    # authenticate and get access token
    auth_response = requests.post(auth_url, auth=HTTPBasicAuth(client_id, client_secret), data={"grant_type": "client_credentials"})
    
    if auth_response.status_code != 200:
        return f"Authentication failed: {auth_response.text}"
    
    access_token = auth_response.json().get("access_token")
    headers = {"Authorization": f"Bearer {access_token}"}
    
    # fetch financial institutions
    response = requests.get(institutions_url, headers=headers)
    
    if response.status_code != 200:
        return f"Failed to fetch institutions: {response.text}"
    
    institutions = response.json()
    return [{"id": inst["id"], "name": inst["name"], "countries": inst["countries"]} for inst in institutions]




# function to extract domain
extract_domain = lambda url: urlparse(url if "://" in url else f"https://{url}").netloc.replace("www.", "")

# Define the isTyposquatting function
def isTyposquatting(legit_domains, scam_domain, threshold=2):
    for legit_domain in legit_domains:
        if Levenshtein.ratio(legit_domain, scam_domain) <= threshold:
            return True
    return False

def format_domain(domain):
    if not domain.startswith(('https://', 'http://', 'www.')):
        return 'https://' + domain
    return domain

In [48]:
# fetch centralized exchanges from coingecko
cex_url = "https://api.coingecko.com/api/v3/exchanges"
gecko_data = fetch_exchanges(cex_url)
# view the first item of the data
gecko_data[0]

Fetched page 1 with 250 exchanges.
Fetched page 2 with 250 exchanges.
Fetched page 3 with 250 exchanges.
Fetched page 4 with 227 exchanges.

{'id': 'binance',
 'name': 'Binance',
 'year_established': 2017,
 'country': 'Cayman Islands',
 'description': 'One of the world’s largest cryptocurrency exchanges by trading volume, offering a wide range of services including spot, futures, and staking options.',
 'url': 'https://www.binance.com/',
 'image': 'https://coin-images.coingecko.com/markets/images/52/small/binance.jpg?1706864274',
 'has_trading_incentive': False,
 'trust_score': 10,
 'trust_score_rank': 1,
 'trade_volume_24h_btc': 196325.5893472316,
 'trade_volume_24h_btc_normalized': 107221.49767585589}

In [49]:
# fetch every exchange protocol from defi llama
url = "https://api.llama.fi/protocols"
llama_data = fetch_exchanges_II(url)
# view the first item of the data
llama_data[0]

{'id': '2269',
 'name': 'Binance CEX',
 'address': None,
 'symbol': '-',
 'url': 'https://www.binance.com',
 'description': 'Binance is a cryptocurrency exchange which is the largest exchange in the world in terms of daily trading volume of cryptocurrencies',
 'chain': 'Multi-Chain',
 'logo': 'https://icons.llama.fi/binance-cex.jpg',
 'audits': '0',
 'audit_note': None,
 'gecko_id': None,
 'cmcId': None,
 'category': 'CEX',
 'chains': ['Bitcoin',
  'Ethereum',
  'Binance',
  'Solana',
  'Ripple',
  'Doge',
  'Tron',
  'Base',
  'Arbitrum',
  'Avalanche',
  'Optimism',
  'Litecoin',
  'Polkadot',
  'Hedera',
  'TON',
  'Near',
  'Polygon',
  'Stellar',
  'Algorand',
  'Aptos',
  'Starknet',
  'Chiliz',
  'Manta',
  'Celo',
  'Op_Bnb',
  'Ronin',
  'zkSync Era',
  'Sui'],
 'module': 'binance/index.js',
 'twitter': 'binance',
 'forkedFrom': [],
 'oracles': [],
 'listedAt': 1668170565,
 'methodology': 'We collect the wallets from this binance blog post https://www.binance.com/en/blog/community/our-commitment-to-transparency-2895840147147652626. We are not counting the Binance Recovery Fund wallet',
 'slug': 'binance-cex',
 'tvl': 138742280810.23273,
 'chainTvls': {'Base': 2058914107.2966926,
  'Algorand': 201777469.4780144,
  'Op_Bnb': 16694222.837912412,
  'Hedera': 540289199.335736,
  'Aptos': 196881015.93957186,
  'Ronin': 15793639.596050944,
  'Manta': 58948123.89162097,
  'Chiliz': 83540620.55017875,
  'Near': 469101742.9632103,
  'Ripple': 5931585945.735259,
  'Stellar': 242290056.7232778,
  'Starknet': 111051086.13072577,
  'Optimism': 863253544.2679529,
  'Litecoin': 640063507.7291589,
  'Avalanche': 919238868.6084853,
  'Sui': 538076.7311354512,
  'Polygon': 264872631.64876443,
  'Celo': 56471990.75166785,
  'Ethereum': 40118004827.79046,
  'Arbitrum': 1620765211.10641,
  'zkSync Era': 5614024.502366856,
  'Binance': 21539630281.24999,
  'Tron': 2728076071.065317,
  'Polkadot': 633191795.6291062,
  'TON': 497692837.7853843,
  'Solana': 7459360074.230038,
  'Bitcoin': 48723565941.83075,
  'Doge': 2745073894.8274965},
 'change_1h': -0.18774611254164597,
 'change_1d': -0.34654535749656645,
 'change_7d': 6.984795977212059,
 'tokenBreakdowns': {},
 'mcap': None}

In [50]:
crypto_exchanges = llama_data + gecko_data

# Print the total number of exchanges fetched
print(f"Total exchanges fetched: {len(crypto_exchanges)}")

Total exchanges fetched: 6643

In [51]:
# Create a set to store unique URLs
unique_urls = set()

# Add URLs from cex_data to the set
for exchange in gecko_data:
    # Normalize by stripping trailing slashes
    unique_urls.add(exchange['url'].rstrip('/')) 

# Create a list to store unique exchanges
unique_exchanges = []

# Add exchanges from cex_data to the unique list
for exchange in gecko_data:
    if exchange['url'].rstrip('/') in unique_urls:
        unique_exchanges.append(exchange)

# Add exchanges from ex_data to the unique list
for exchange in llama_data:
    if exchange['url'].rstrip('/') in unique_urls:
        unique_exchanges.append(exchange)

# Print the total number of unique exchanges fetched
# print(f"Total unique exchanges fetched: {len(unique_exchanges)}")

unique_exchanges

[{'id': 'binance',
  'name': 'Binance',
  'year_established': 2017,
  'country': 'Cayman Islands',
  'description': 'One of the world’s largest cryptocurrency exchanges by trading volume, offering a wide range of services including spot, futures, and staking options.',
  'url': 'https://www.binance.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/52/small/binance.jpg?1706864274',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 1,
  'trade_volume_24h_btc': 196325.5893472316,
  'trade_volume_24h_btc_normalized': 107221.49767585589},
 {'id': 'bybit_spot',
  'name': 'Bybit',
  'year_established': 2018,
  'country': 'British Virgin Islands',
  'description': 'Bybit is the world’s second-largest cryptocurrency exchange by trading volume, serving a global community of over 60 million users. Founded in 2018, Bybit is redefining openness in the decentralized world by creating a simpler, open and equal ecosystem for everyone. With a strong focus on Web3, Bybit partners strategically with leading blockchain protocols to provide robust infrastructure and drive on-chain innovation. Renowned for its secure custody, diverse marketplaces, intuitive user experience, and advanced blockchain tools, Bybit bridges the gap between TradFi and DeFi, empowering builders, creators, and enthusiasts to unlock the full potential of Web3. Discover the future of decentralized finance at Bybit.com.',
  'url': 'https://www.bybit.com',
  'image': 'https://coin-images.coingecko.com/markets/images/698/small/bybit_spot.png?1706864649',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 2,
  'trade_volume_24h_btc': 31346.602304352917,
  'trade_volume_24h_btc_normalized': 31346.602304352917},
 {'id': 'okex',
  'name': 'OKX',
  'year_established': 2017,
  'country': 'Seychelles',
  'description': 'OKX is a leading global cryptocurrency exchange offering diverse trading options, advanced security, and Web3 integration for millions of users worldwide.\r\n',
  'url': 'https://www.okx.com',
  'image': 'https://coin-images.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1706864283',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 3,
  'trade_volume_24h_btc': 29056.507936072816,
  'trade_volume_24h_btc_normalized': 29056.507936072816},
 {'id': 'gdax',
  'name': 'Coinbase Exchange',
  'year_established': 2012,
  'country': 'United States',
  'description': 'A leading U.S.-based exchange known for its regulatory compliance, user-friendly interface, and support for fiat-to-crypto transactions.',
  'url': 'https://www.coinbase.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1706864258',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 4,
  'trade_volume_24h_btc': 27450.028301110877,
  'trade_volume_24h_btc_normalized': 27450.028301110877},
 {'id': 'bitget',
  'name': 'Bitget',
  'year_established': 2018,
  'country': 'Seychelles',
  'description': "Established in 2018, Bitget is the world's leading cryptocurrency exchange and Web3 company. Serving over 100 million users in 150+ countries and regions, the Bitget exchange is committed to helping users trade smarter with its pioneering copy trading feature and other trading solutions, while offering real-time access to Bitcoin price, Ethereum price, and other cryptocurrency prices. Formerly known as BitKeep, Bitget Wallet is a world-class multi-chain crypto wallet that offers an array of comprehensive Web3 solutions and features including wallet functionality, token swap, NFT Marketplace, DApp browser, and more. Bitget is at the forefront of driving crypto adoption through strategic partnerships, such as its role as the Official Crypto Partner of the World's Top Football League, LALIGA, in EASTERN, SEA and LATAM market, as well as a global partner of Turkish National athletes Buse Tosun Çavuşoğlu (Wrestling world champion), Samet Gümüş (Boxing gold medalist) and İlkin Aydın (Volleyball national team), to inspire the global community to embrace the future of cryptocurrency.",
  'url': 'https://www.bitget.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/540/small/2023-07-25_21.47.43.jpg?1706864507',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 5,
  'trade_volume_24h_btc': 27239.445907630023,
  'trade_volume_24h_btc_normalized': 27239.445907630023},
 {'id': 'crypto_com',
  'name': 'Crypto.com Exchange',
  'year_established': 2019,
  'country': 'Malta',
  'description': 'Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards',
  'url': 'https://crypto.com/exchange',
  'image': 'https://coin-images.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1706864542',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 6,
  'trade_volume_24h_btc': 23596.330689848535,
  'trade_volume_24h_btc_normalized': 15973.043134026768},
 {'id': 'kraken',
  'name': 'Kraken',
  'year_established': 2011,
  'country': 'United States',
  'description': 'Kraken is a San Francisco-based cryptocurrency exchange, offering a wide range of trading services for various cryptocurrencies and known for its robust security and regulatory compliance efforts.\r\n',
  'url': 'https://www.kraken.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/29/small/kraken.jpg?1706864265',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 7,
  'trade_volume_24h_btc': 13226.92323704465,
  'trade_volume_24h_btc_normalized': 13226.92323704465},
 {'id': 'backpack_exchange',
  'name': 'Backpack Exchange ',
  'year_established': 2023,
  'country': 'British Virgin Islands',
  'description': 'A next-gen cryptocurrency exchange. ',
  'url': 'https://backpack.exchange/',
  'image': 'https://coin-images.coingecko.com/markets/images/1387/small/backpack.jpeg?1708663541',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 8,
  'trade_volume_24h_btc': 347.21924203676366,
  'trade_volume_24h_btc_normalized': 347.21924203676366},
 {'id': 'binance_us',
  'name': 'Binance US',
  'year_established': 2019,
  'country': 'United States',
  'description': "Binance U.S. is the American branch of the world's largest cryptocurrency exchange, Binance, launched to comply with U.S. regulations and offering over 100 cryptocurrencies with competitive trading fees.",
  'url': 'https://www.binance.us/',
  'image': 'https://coin-images.coingecko.com/markets/images/469/small/Binance.png?1706864454',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 9,
  'trade_volume_24h_btc': 92.68309470233447,
  'trade_volume_24h_btc_normalized': 92.68309470233447},
 {'id': 'hashkey-global',
  'name': 'HashKey Global',
  'year_established': 2018,
  'country': 'Bermuda',
  'description': "HashKey Global is the flagship digital asset exchange under HashKey Group, offering licensed digital asset trading services to global users. HashKey Global is licensed in under the Bermuda Monetary Authority's full Digital Asset Business investor protection regime under a Class F Full License.   HashKey Global adopts the compliance, security, and audit best practices of HashKey Exchange (the largest licensed digital asset exchange in Hong Kong), with features such as asset segregation,  information security controls, insurance, independent auditing, and payments settlement.  HashKey Global has a compliant listing system and will offer mainstream trading services like LaunchPad, futures, leverage and staking.  HashKey Global is the core of HashKey Group's global licensed exchange landscape.  Note: HashKey Global does not conduct business in the United States, mainland China, Hong Kong, and certain sanctioned countries.  For more details :global.hashkey.com ",
  'url': 'https://global.hashkey.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/1582/small/20240422-181043.jpg?1715067065',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 10,
  'trade_volume_24h_btc': 27.625313626803027,
  'trade_volume_24h_btc_normalized': 27.625313626803027},
 {'id': 'mxc',
  'name': 'MEXC',
  'year_established': 2018,
  'country': 'Seychelles',
  'description': 'Established in April 2018, MEXC is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.',
  'url': 'https://www.mexc.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/409/small/MEXC_logo_square.jpeg?1706864416',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 11,
  'trade_volume_24h_btc': 33684.98113299277,
  'trade_volume_24h_btc_normalized': 33684.98113299277},
 {'id': 'huobi',
  'name': 'HTX',
  'year_established': 2013,
  'country': 'Seychelles',
  'description': 'HTX (previously Huobi) is a leading cryptocurrency exchange recognized for its strong security measures and a wide range of trading options. With a user-friendly interface and high liquidity, it caters to both novice and experienced traders while offering various incentives like staking and referral programs.',
  'url': 'https://www.huobi.com',
  'image': 'https://coin-images.coingecko.com/markets/images/25/small/htx.png?1721712842',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 12,
  'trade_volume_24h_btc': 38799.85190116794,
  'trade_volume_24h_btc_normalized': 30169.45578728417},
 {'id': 'gate',
  'name': 'Gate.io',
  'year_established': 2013,
  'country': 'Panama',
  'description': 'Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.',
  'url': 'https://www.gate.io/',
  'image': 'https://coin-images.coingecko.com/markets/images/60/small/gate_io_logo1.jpg?1706864280',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 13,
  'trade_volume_24h_btc': 28111.027681128642,
  'trade_volume_24h_btc_normalized': 28111.027681128642},
 {'id': 'coinw',
  'name': 'CoinW',
  'year_established': 2017,
  'country': 'United Arab Emirates',
  'description': 'What Is CoinW? \r\nCoinW stands as a pinnacle in the world of crypto trading platforms, where our unwavering commitment to security, transparency, and user-centric principles sets us apart. Powered by cutting-edge technology, boasting deep liquidity, and offering support for a diverse array of cryptocurrencies, we have cultivated a vast and dedicated user base, solidifying our position as one of the most secure exchanges globally. \r\n \r\nDedicated to upholding the highest regulatory standards, we prioritize security, transparency, and compliance to contribute actively to the advancement of the crypto industry. At CoinW, we take pride in serving over 13 million users worldwide, earning our reputation as a beacon of security and reliability in the dynamic realm of cryptocurrency. Join us on this journey, where your assets are safeguarded, and your trading experience is elevated to new heights. Serving customers in over 200 regions and countries, CoinW is dedicated to providing a seamless and localized trading experience. \r\n \r\nAs a forward-thinking crypto trading platform, we prioritize collaboration with international regulatory bodies and organizations, contributing to the establishment of a safe and secure environment for our users. \r\n \r\nWho Are the Founders of CoinW? \r\nIncepted in 2017 by a fusion of crypto, cybersecurity, and finance virtuosos with a robust workforce comprising over 1,000 talents representing 30 diverse nations, CoinW stands as the quintessential embodiment of a global and professional entity. \r\n \r\nWhen Did CoinW Launch? \r\nCoinW was launched in 2017. \r\n \r\nWhat Coins Are Supported on CoinW? \r\nCoinW boasts a vast array of over 1,000 listed crypto tokens, offering more than 500 spot trading pairs. Popular coins include BTC, ETH, XRP, PEPE, DOGE, SHIB, LTC, APT and more. \r\n \r\nHow Much Are CoinW Fees? \r\nWhen users conduct currency transactions on CoinW, the platform will charge users a certain fee to support the operation of the platform. User fees for makers and takers on the platform will be charged according to different rules. Currently, the basic fees for maker is 0.01% and taker is 0.06% on the platform. \r\n \r\nIs It Possible To Use Leverage or Margin Trading on CoinW? \r\nCoinW empowers traders seeking strategic leverage through our comprehensive options for both spot and Futures trading. Our platform offers unparalleled flexibility, allowing users to utilize leverage ratios of up to 200x in Futures and 6x in ETF trading. This means that traders can amplify their positions, opening the door to potential profit maximization in crypto market.',
  'url': 'https://www.coinw.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/1172/small/coinw_new_logo.png?1713879109',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 14,
  'trade_volume_24h_btc': 14682.69470217996,
  'trade_volume_24h_btc_normalized': 14682.69470217996},
 {'id': 'whitebit',
  'name': 'WhiteBIT',
  'year_established': 2018,
  'country': 'Lithuania',
  'description': 'WhiteBIT is a European centralized cryptocurrency exchange, offering a secure platform for trading with competitive fees and advanced trading tools.\r\n',
  'url': 'https://whitebit.com',
  'image': 'https://coin-images.coingecko.com/markets/images/418/small/800_800.jpg?1706864419',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 15,
  'trade_volume_24h_btc': 8706.201650040864,
  'trade_volume_24h_btc_normalized': 8706.201650040864},
 {'id': 'latoken',
  'name': 'LATOKEN',
  'year_established': 2017,
  'country': 'Cayman Islands',
  'description': 'LATOKEN is a cryptocurrency exchange, recognized as a leading platform for Initial Exchange Offerings (IEOs).',
  'url': 'https://latoken.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/124/small/latoken.png?1706864301',
  'has_trading_incentive': False,
  'trust_score': 8,
  'trust_score_rank': 16,
  'trade_volume_24h_btc': 6898.660442843512,
  'trade_volume_24h_btc_normalized': 6898.660442843512},
 {'id': 'kucoin',
  'name': 'KuCoin',
  'year_established': 2017,
  'country': 'Seychelles',
  'description': "Launched in September 2017, KuCoin is a global cryptocurrency exchange with its operational headquarters in Seychelles. As a user-oriented platform with a focus on inclusiveness and community action reach, it offers over 800 digital assets and currently provides Spot trading, Margin trading, P2P Fiat trading, Futures trading, Staking, and Lending to its 30 million users in more than 200 countries and regions. KuCoin is currently one of the top 5 crypto exchanges. In 2023, KuCoin was named one of the Best Crypto Exchanges by Forbes and recognized as a highly commended global exchange in Finder's 2023 Global Cryptocurrency Trading Platform Awards. Learn more at https://www.kucoin.com.",
  'url': 'https://www.kucoin.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/61/small/kucoin.png?1706864282',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 17,
  'trade_volume_24h_btc': 10420.113724832268,
  'trade_volume_24h_btc_normalized': 6682.6985983866025},
 {'id': 'bingx',
  'name': 'BingX',
  'year_established': 2018,
  'country': 'British Virgin Islands',
  'description': "Founded in 2018, BingX is a leading crypto exchange, serving over 10 million users worldwide. BingX offers diversified products and services, including spot, derivatives, copy trading, and asset management – all designed for the evolving needs of users, from beginners to professionals. \r\n\r\nBingX is committed to providing a trustworthy platform that empowers users with innovative tools and features to elevate their trading proficiency. In 2024, BingX proudly became Chelsea FC's principal partner, marking an exciting debut in the world of sports.",
  'url': 'https://bingx.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1706864837',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 18,
  'trade_volume_24h_btc': 3196.6410319772804,
  'trade_volume_24h_btc_normalized': 3196.6410319772804},
 {'id': 'bitfinex',
  'name': 'Bitfinex',
  'year_established': 2012,
  'country': 'British Virgin Islands',
  'description': 'Bitfinex, operated by iFinex Inc., is a prominent cryptocurrency exchange known for its advanced trading features, including spot and derivatives markets, margin trading, and support.',
  'url': 'https://www.bitfinex.com',
  'image': 'https://coin-images.coingecko.com/markets/images/4/small/BItfinex.png?1706864245',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 19,
  'trade_volume_24h_btc': 1640.15038154426,
  'trade_volume_24h_btc_normalized': 1409.6269332701675},
 {'id': 'gemini',
  'name': 'Gemini',
  'year_established': 2014,
  'country': 'United States',
  'description': 'Gemini is a regulated cryptocurrency exchange founded by Cameron and Tyler Winklevoss, allowing users to buy, sell, and securely store cryptocurrencies. Known for its strong emphasis on security and compliance, Gemini also offers features like its own stablecoin, the Gemini dollar, and a tiered service catering to both casual investors and professional traders.',
  'url': 'https://www.gemini.com/',
  'image': 'https://coin-images.coingecko.com/markets/images/50/small/gemini.png?1706864273',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 20,
  'trade_volume_24h_btc': 941.3127238629584,
  'trade_volume_24h_btc_normalized': 941.3127238629584},
 {'id': 'luno',
  'name': 'Luno',
  'year_established': 2013,
  'country': 'Singapore',
  'description': 'Luno is a cryptocurrency exchange and wallet service, focused on facilitating the adoption of cryptocurrencies like Bitcoin and Ethereum. With a user-friendly platform and strong security measures, Luno also offers educational resources to help beginners navigate the crypto landscape.',
  'url': 'https://www.luno.com',
  'image': 'https://coin-images.coingecko.com/markets/images/33/small/RGB_LUNO_SYMBOL_NAVY_BLUE_1.png?1706864266',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 21,
  'trade_volume_24h_btc': 143.32711802166506,
  'trade_volume_24h_btc_normalized': 143.32711802166506},
 {'id': 'wootrade',
  'name': 'WOO X',
  'year_established': 2019,
  'country': 'Seychelles',
  'description': "WOO X is a global centralized crypto futures and spot trading platform offering best-in-class liquidity and price execution. WOO X has an average daily volume exceeding $600 million and is home to hundreds of thousands of traders worldwide. WOO X traders benefit from radical transparency through our industry-first live Proof of Reserves & liabilities dashboard and the company's mission to maintain the trust of its growing community of traders.\r\n",
  'url': 'https://woox.io/',
  'image': 'https://coin-images.coingecko.com/markets/images/683/small/woo.png?1706864629',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 22,
  'trade_volume_24h_btc': 58.642256899828574,
  'trade_volume_24h_btc_normalized': 58.642256899828574},
 {'id': 'coindcx',
  'name': 'CoinDCX',
  'year_established': 2018,
  'country': 'Singapore',

In [52]:
with open("legit-exchanges.json", "w") as file:
    json.dump(unique_exchanges, file)

In [53]:
# fetch other legitimate websites asides crypto
# to ensure balance in datasets.
other_websites = "https://raw.githubusercontent.com/seigdev/resources/refs/heads/main/top-websites.csv"

other_raw = fetch_data_csv(other_websites)

others_df = pd.DataFrame(other_raw)

others_df = others_df.drop(columns=0)

others_df = others_df.rename(columns={1: 'url'})

In [54]:

df_raw = pd.read_json("legit-exchanges.json")

# copy the name and urls columns to a new dataframe
crypto_df = df_raw[['url']].copy()

legit_df = pd.concat([crypto_df, others_df], ignore_index=True)

legit_df["url"] = legit_df["url"].apply(format_domain)

# assign string labels to legitimate urls
legit_df.loc[:, 'label'] = 'legit'

# assign string labels to legitimate urls
legit_df.loc[:, 'label_no'] = '0'

# select first 100
legit_df = legit_df[:50000]

legit_df

                              url  label label_no
0        https://www.binance.com/  legit        0
1           https://www.bybit.com  legit        0
2             https://www.okx.com  legit        0
3       https://www.coinbase.com/  legit        0
4         https://www.bitget.com/  legit        0
...                           ...    ...      ...
49995       https://ecatholic.com  legit        0
49996          https://reclaim.ai  legit        0
49997       https://gotickets.com  legit        0
49998            https://ctfs.com  legit        0
49999  https://transitchicago.com  legit        0

[50000 rows x 3 columns]

In [55]:
# url to fetch scam urls from eth-phishing-detect
scam_url = "https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/config.json"
scam_ex = fetch_exchanges_II(scam_url)

# fetch the list of blacklist urls
blacklist = scam_ex["blacklist"]

In [56]:
blacklist = blacklist_toMap(blacklist)

In [57]:
with open("scam-exchanges.json", "w") as file:
    json.dump(blacklist, file)

In [58]:
blacklist_raw = pd.read_json("scam-exchanges.json")

# copy the name and urls columns to a new dataframe
scam_df = blacklist_raw[['url']].copy()

scam_df["url"] = scam_df["url"].apply(format_domain)

# assign string labels to legitimate urls
scam_df.loc[:, 'label'] = 'scam'

# assign string labels to legitimate urls
scam_df.loc[:, 'label_no'] = '1'

# select first 100
# scam_df = scam_df.sample(n=100000, random_state=42).reset_index(drop=True)
scam_df = scam_df[:100000]

scam_df

                                      url label label_no
0          https://ogntoken-migration.icu  scam        1
1      https://fazla-rabby-rady.github.io  scam        1
2                 https://polymaraket.com  scam        1
3                  https://predictdex.com  scam        1
4                   https://polymarket.mx  scam        1
...                                   ...   ...      ...
99995             https://blastclaim.pics  scam        1
99996        https://shovel-manta.network  scam        1
99997   https://bouncebit-claim.pages.dev  scam        1
99998     https://arbitrum.wtrust-pad.top  scam        1
99999       https://pucmoon-whitelist.org  scam        1

[100000 rows x 3 columns]

In [59]:
# merge both the legit and scam urls together
urls_df = pd.concat([legit_df, scam_df], ignore_index=True)

# shuffle the urls across the dataframe
urls_df = urls_df.sample(frac=1, random_state=42).reset_index(drop=True)

urls_df

                                     url  label label_no
0             https://pan-cakev-app.info   scam        1
1                    https://harrods.com  legit        0
2          https://claim.dogshouse.store   scam        1
3          https://circle-foundation.com   scam        1
4                     https://wepdex.com   scam        1
...                                  ...    ...      ...
149995            https://hualeebaix.fun   scam        1
149996        https://myetnherwallet.com   scam        1
149997        https://giveawayton.online   scam        1
149998  https://trustwallet-support.tech   scam        1
149999               https://voxedex.top   scam        1

[150000 rows x 3 columns]

In [60]:
urls_df.to_json('crypto_data.json', orient='records', lines=False)